### ISSUE TITLE
 User to add a new centre and a new trial using the content uploader tool 

### ISSUE THREAD

**Issue by ChandrimaSengupta** [Image-X-Institute/The-Real-Time-Imaging-Database#10]

**Comment by Gahhh** [comment]
Currently, the centre and trial are fixed in the content uploader, at here:  https://github.com/Image-X-Institute/The-Real-Time-Imaging-Database/blob/a93a70766cdefc4467d00c224e6747b84203454a/src/content_uploader/ContentUploader.py#L211

So if the user wants to add new centre and trial, we may need to create two new tables to store the name of centre and trial, and also modify the data_service to be able to read and create new centre and trial for the frontend user. I will work on this today and tomorrow.

**Comment by ind3r** [comment]
The auth_db_schema.sql already has the trial and centre tables so these can be used by the content uploader (via an API exposed through data service). I think the local copies of the site and trial in content uploader was added to address the scenario when the content uploader didn't have direct access to the data service (such as using one drive etc.) but it makes sense to remove this hardcoding from the content uploader code.
