### ISSUE TITLE
Uploading data to sharedrive

### ISSUE THREAD

**Issue by ChandrimaSengupta** [Image-X-Institute/The-Real-Time-Imaging-Database#36]
Uploading data to sharedrive instead of a test database.

**Comment by Gahhh** [comment]
Previously the data folder was connected to sharedrive. But it was used Indrajit's Unikey. I tried to use my unikey to connect the share drive. The issue is when the server reboot each time, we have to re-connect the share drive by entering the unikey password manually. Grieve lab also had this issue, but they have a special account for the server, and they saved the unikey and password into the server, so the server could auto login every time. I think we may also need an account for the server to connect the RDS.
